 apiVersion: v1
 kind: Service
 metadata:
   name: ibm-cloud-ingress
   namespace: kube-system
 spec:
   type: LoadBalancer
   selector:
     app: ibm-cloud-ingress
   ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443